SEARCH_TITLES = [
    "Data Engineer",
    "AI Engineer",
]

CONCURRENCY_LIMIT = 15

# Run with ?test=true on /scrape to use only these 10 companies
TEST_COMPANIES = [
    "Amazon",
    "Apple",
    "Microsoft",
    "Fannie Mae",
    "Freddie Mac",
    "Humana",
    "Cigna",
    "Cardinal Health",
    "Pfizer",
    "Sysco",
]

# ats_type values: "greenhouse" | "workday" | "generic"
# greenhouse_token: Greenhouse board slug (None if not Greenhouse)
# search_url_template: URL with {title} placeholder for generic/workday scrapers
# enabled: False = skip (bad URL or needs investigation)
COMPANIES = [
    # ── Workday ──────────────────────────────────────────────────────────────
    {
        "company_name": "Fannie Mae",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://fanniemae.wd1.myworkdayjobs.com/FannieMaeCareers",
        "search_url_template": "https://fanniemae.wd1.myworkdayjobs.com/FannieMaeCareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Freddie Mac",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://freddiemac.wd5.myworkdayjobs.com/External",
        "search_url_template": "https://freddiemac.wd5.myworkdayjobs.com/External?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Humana",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site",
        "search_url_template": "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Cigna",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://cigna.wd5.myworkdayjobs.com/cignacareers",
        "search_url_template": "https://cigna.wd5.myworkdayjobs.com/cignacareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Cardinal Health",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://cardinalhealth.wd1.myworkdayjobs.com/EXT",
        "search_url_template": "https://cardinalhealth.wd1.myworkdayjobs.com/EXT?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Raytheon Technologies",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway",
        "search_url_template": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Tesla",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.tesla.com/careers/search",
        "search_url_template": "https://www.tesla.com/careers/search#/?keyword={title}&department=engineering",
        "enabled": True,
    },
    {
        "company_name": "Goldman Sachs Group",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://higher.gs.com/roles",
        "search_url_template": "https://higher.gs.com/roles?q={title}",
        "enabled": True,
    },
    # ── Custom JSON API scrapers (no Playwright needed) ──────────────────────
    {
        "company_name": "Amazon",
        "ats_type": "amazon",
        "greenhouse_token": None,
        "career_url": "https://www.amazon.jobs/en/search",
        "search_url_template": "https://www.amazon.jobs/en/search.json?base_query={title}&country%5B%5D=US&result_limit=10",
        "enabled": True,
    },
    {
        "company_name": "Apple",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.apple.com/en-us/search",
        "search_url_template": "https://jobs.apple.com/en-us/search?search={title}&sort=relevance",
        "enabled": True,
    },
    {
        "company_name": "Microsoft",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.microsoft.com/v2/global/en/search",
        "search_url_template": "https://careers.microsoft.com/v2/global/en/search?q={title}",
        "enabled": True,
    },

    # ── Workday ──────────────────────────────────────────────────────────────
    {
        "company_name": "Pfizer",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers",
        "search_url_template": "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Sysco",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://sysco.wd5.myworkdayjobs.com/syscocareers",
        "search_url_template": "https://sysco.wd5.myworkdayjobs.com/syscocareers?q={title}",
        "enabled": True,
    },

    # ── Generic career pages ─────────────────────────────────────────────────
    {
        "company_name": "Walmart",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.walmart.com/results",
        "search_url_template": "https://careers.walmart.com/results?q={title}&page=1",
        "enabled": True,
    },
    {
        "company_name": "Exxon Mobil",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://corporate.exxonmobil.com/careers",
        "search_url_template": "https://corporate.exxonmobil.com/careers#career-search",
        "enabled": True,
    },
    {
        "company_name": "UnitedHealth Group",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.unitedhealthgroup.com/",
        "search_url_template": "https://careers.unitedhealthgroup.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "CVS Health",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.cvshealth.com/us/en/search-results",
        "search_url_template": "https://jobs.cvshealth.com/us/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Berkshire Hathaway",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers-guard.icims.com/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Alphabet",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.google.com/",
        "search_url_template": "https://careers.google.com/jobs/results/?q={title}&location=United+States",
        "enabled": True,
    },
    {
        "company_name": "McKesson",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.mckesson.com",
        "search_url_template": "https://careers.mckesson.com/en/search-jobs/{title}/733/1",
        "enabled": True,
    },
    {
        "company_name": "Chevron",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.chevron.com/find-a-job",
        "search_url_template": "https://careers.chevron.com/find-a-job?q={title}",
        "enabled": True,
    },
    {
        "company_name": "AmerisourceBergen",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.cencora.com/us/en/home",
        "search_url_template": "https://careers.cencora.com/us/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Costco Wholesale",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.costco.com/jobs",
        "search_url_template": "https://careers.costco.com/jobs?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Marathon Petroleum",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.marathonpetroleum.com/Jobs/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Phillips 66",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.phillips66.com/careers/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Valero Energy",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.valero.com/careers",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Ford Motor",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.ford.com/",
        "search_url_template": "https://careers.ford.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "Home Depot",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.homedepot.com/job-search-results/",
        "search_url_template": "https://careers.homedepot.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "General Motors",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://search-careers.gm.com/en/working-at-gm/",
        "search_url_template": "https://search-careers.gm.com/en/working-at-gm/?search={title}",
        "enabled": True,
    },
    {
        "company_name": "Elevance Health",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.elevancehealth.com/jobs",
        "search_url_template": "https://careers.elevancehealth.com/jobs?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "JPMorgan Chase",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs",
        "search_url_template": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "Kroger",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.kroger.com/",
        "search_url_template": "https://jobs.kroger.com/search/?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Centene",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.centene.com/us/en",
        "search_url_template": "https://jobs.centene.com/us/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Verizon Communications",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://mycareer.verizon.com/career-paths/corporate/",
        "search_url_template": "https://mycareer.verizon.com/jobs/#q={title}&t=Jobs",
        "enabled": True,
    },
    {
        "company_name": "AT&T",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.att.com/careers/",
        "search_url_template": "https://www.att.com/careers/search.html?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Meta Platforms",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.metacareers.com/jobs/",
        "search_url_template": "https://www.metacareers.com/jobs/?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Bank of America",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.bankofamerica.com/en-us",
        "search_url_template": "https://careers.bankofamerica.com/en-us/search?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Target",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.target.com/",
        "search_url_template": "https://jobs.target.com/search/?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Dell Technologies",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.dell.com/en/search-jobs",
        "search_url_template": "https://jobs.dell.com/en/search-jobs/{title}/1",
        "enabled": True,
    },
    {
        "company_name": "Archer Daniels Midland",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://sjobs.brassring.com/TGnewUI/Search/home/Home?partnerid=25416&siteid=5998",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Citigroup",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.citi.com/",
        "search_url_template": "https://jobs.citi.com/search-jobs/{title}/287/1",
        "enabled": True,
    },
    {
        "company_name": "Johnson & Johnson",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.careers.jnj.com/en/",
        "search_url_template": "https://www.careers.jnj.com/en/jobs?search={title}&country=United+States",
        "enabled": True,
    },
    {
        "company_name": "FedEx",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.fedex.com/jobs",
        "search_url_template": "https://careers.fedex.com/jobs#q={title}&t=Jobs",
        "enabled": True,
    },
    {
        "company_name": "Energy Transfer",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.energytransfer.com/careers/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "State Farm Insurance",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.statefarm.com/main/",
        "search_url_template": "https://jobs.statefarm.com/main/jobs?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "PepsiCo",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.pepsico.com/en/careers",
        "search_url_template": "https://www.pepsico.com/en/careers/search?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Wells Fargo",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.wellsfargo.com/about/careers/",
        "search_url_template": "https://www.wellsfargo.com/about/careers/search?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Walt Disney",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.disneycareers.com/",
        "search_url_template": "https://jobs.disneycareers.com/search-jobs/{title}/391/1",
        "enabled": True,
    },
    {
        "company_name": "ConocoPhillips",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.conocophillips.com/job-search-results/",
        "search_url_template": "https://careers.conocophillips.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "Procter & Gamble",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.pgcareers.com/",
        "search_url_template": "https://www.pgcareers.com/global/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "General Electric",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.gecareers.com/global/en/search-results",
        "search_url_template": "https://jobs.gecareers.com/global/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Albertsons",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.albertsons.com/careers.html",
        "search_url_template": None,
        "enabled": True,
    },

    # ── Disabled (bad/unverified portal URLs) ────────────────────────────────
    {
        "company_name": "Walgreens Boots Alliance",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.walgreens.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "UPS",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.jobs-ups.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "Lowe's",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://talent.lowes.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "MetLife",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.metlife.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "Comcast",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.comcast.com/",
        "search_url_template": "https://jobs.comcast.com/search-jobs/{title}",
        "enabled": False,
    },
]
