SEARCH_TITLES = [
    "Data Engineer",
    "AI Engineer",
]

CONCURRENCY_LIMIT = 15

# Run with ?test=true on /scrape to use only these 10 companies
TEST_COMPANIES = [
    "Amazon",
    "Apple",
    "Microsoft",
    "Fannie Mae",
    "Freddie Mac",
    "Humana",
    "Cigna",
    "Cardinal Health",
    "Pfizer",
    "Sysco",
]

# ats_type values: "greenhouse" | "workday" | "generic"
# greenhouse_token: Greenhouse board slug (None if not Greenhouse)
# search_url_template: URL with {title} placeholder for generic/workday scrapers
# enabled: False = skip (bad URL or needs investigation)
COMPANIES = [
    # ── Workday ──────────────────────────────────────────────────────────────
    {
        "company_name": "Fannie Mae",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://fanniemae.wd1.myworkdayjobs.com/FannieMaeCareers",
        "search_url_template": "https://fanniemae.wd1.myworkdayjobs.com/FannieMaeCareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Freddie Mac",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://freddiemac.wd5.myworkdayjobs.com/External",
        "search_url_template": "https://freddiemac.wd5.myworkdayjobs.com/External?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Humana",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site",
        "search_url_template": "https://humana.wd5.myworkdayjobs.com/Humana_External_Career_Site?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Cigna",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://cigna.wd5.myworkdayjobs.com/cignacareers",
        "search_url_template": "https://cigna.wd5.myworkdayjobs.com/cignacareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Cardinal Health",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://cardinalhealth.wd1.myworkdayjobs.com/EXT",
        "search_url_template": "https://cardinalhealth.wd1.myworkdayjobs.com/EXT?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Raytheon Technologies",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway",
        "search_url_template": "https://globalhr.wd5.myworkdayjobs.com/REC_RTX_Ext_Gateway?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Tesla",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.tesla.com/careers/search",
        "search_url_template": "https://www.tesla.com/careers/search#/?keyword={title}&department=engineering",
        "enabled": True,
    },
    {
        "company_name": "Goldman Sachs Group",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://higher.gs.com/roles",
        "search_url_template": "https://higher.gs.com/roles?q={title}",
        "enabled": True,
    },
    # ── Custom JSON API scrapers (no Playwright needed) ──────────────────────
    {
        "company_name": "Amazon",
        "ats_type": "amazon",
        "greenhouse_token": None,
        "career_url": "https://www.amazon.jobs/en/search",
        "search_url_template": "https://www.amazon.jobs/en/search.json?base_query={title}&country%5B%5D=US&result_limit=10",
        "enabled": True,
    },
    {
        "company_name": "Apple",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.apple.com/en-us/search",
        "search_url_template": "https://jobs.apple.com/en-us/search?search={title}&sort=relevance",
        "enabled": True,
    },
    {
        "company_name": "Microsoft",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.microsoft.com/v2/global/en/search",
        "search_url_template": "https://careers.microsoft.com/v2/global/en/search?q={title}",
        "enabled": True,
    },

    # ── Workday ──────────────────────────────────────────────────────────────
    {
        "company_name": "Pfizer",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers",
        "search_url_template": "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Sysco",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://sysco.wd5.myworkdayjobs.com/syscocareers",
        "search_url_template": "https://sysco.wd5.myworkdayjobs.com/syscocareers?q={title}",
        "enabled": True,
    },

    # ── Generic career pages ─────────────────────────────────────────────────
    {
        "company_name": "Walmart",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.walmart.com/results",
        "search_url_template": "https://careers.walmart.com/results?q={title}&page=1",
        "enabled": True,
    },
    {
        "company_name": "Exxon Mobil",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://corporate.exxonmobil.com/careers",
        "search_url_template": "https://corporate.exxonmobil.com/careers#career-search",
        "enabled": True,
    },
    {
        "company_name": "UnitedHealth Group",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.unitedhealthgroup.com/",
        "search_url_template": "https://careers.unitedhealthgroup.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "CVS Health",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.cvshealth.com/us/en/search-results",
        "search_url_template": "https://jobs.cvshealth.com/us/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Berkshire Hathaway",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers-guard.icims.com/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Alphabet",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.google.com/",
        "search_url_template": "https://careers.google.com/jobs/results/?q={title}&location=United+States",
        "enabled": True,
    },
    {
        "company_name": "McKesson",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.mckesson.com",
        "search_url_template": "https://careers.mckesson.com/en/search-jobs/{title}/733/1",
        "enabled": True,
    },
    {
        "company_name": "Chevron",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.chevron.com/find-a-job",
        "search_url_template": "https://careers.chevron.com/find-a-job?q={title}",
        "enabled": True,
    },
    {
        "company_name": "AmerisourceBergen",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.cencora.com/us/en/home",
        "search_url_template": "https://careers.cencora.com/us/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Costco Wholesale",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.costco.com/jobs",
        "search_url_template": "https://careers.costco.com/jobs?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Marathon Petroleum",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.marathonpetroleum.com/Jobs/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Phillips 66",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.phillips66.com/careers/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Valero Energy",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.valero.com/careers",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Ford Motor",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.ford.com/",
        "search_url_template": "https://careers.ford.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "Home Depot",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.homedepot.com/job-search-results/",
        "search_url_template": "https://careers.homedepot.com/job-search-results/?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "General Motors",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://search-careers.gm.com/en/working-at-gm/",
        "search_url_template": "https://search-careers.gm.com/en/working-at-gm/?search={title}",
        "enabled": True,
    },
    {
        "company_name": "Elevance Health",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://elevancehealth.wd1.myworkdayjobs.com/ANT",
        "search_url_template": "https://elevancehealth.wd1.myworkdayjobs.com/ANT?q={title}",
        "enabled": True,
    },
    {
        "company_name": "JPMorgan Chase",
        "ats_type": "oracle",
        "greenhouse_token": None,
        "career_url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs",
        "search_url_template": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?keyword={title}",
        "enabled": True,
    },
    {
        "company_name": "Kroger",
        "ats_type": "oracle",
        "greenhouse_token": None,
        "career_url": "https://eluq.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/jobs",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Centene",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.centene.com/us/en",
        "search_url_template": "https://jobs.centene.com/us/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Verizon Communications",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://mycareer.verizon.com/career-paths/corporate/",
        "search_url_template": "https://mycareer.verizon.com/jobs/#q={title}&t=Jobs",
        "enabled": True,
    },
    {
        "company_name": "AT&T",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.att.com/careers/",
        "search_url_template": "https://www.att.com/careers/search.html?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Meta Platforms",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.metacareers.com/jobs",
        "search_url_template": "https://www.metacareers.com/jobs?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Bank of America",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://ghr.wd1.myworkdayjobs.com/lateral-us",
        "search_url_template": "https://ghr.wd1.myworkdayjobs.com/lateral-us?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Target",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://target.wd5.myworkdayjobs.com/targetcareers",
        "search_url_template": "https://target.wd5.myworkdayjobs.com/targetcareers?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Dell Technologies",
        "ats_type": "oracle",
        "greenhouse_token": None,
        "career_url": "https://iawmqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Archer Daniels Midland",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://sjobs.brassring.com/TGnewUI/Search/home/Home?partnerid=25416&siteid=5998",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Citigroup",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.citi.com/",
        "search_url_template": "https://jobs.citi.com/search-jobs/{title}/287/1",
        "enabled": True,
    },
    {
        "company_name": "Johnson & Johnson",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.careers.jnj.com/en/",
        "search_url_template": "https://www.careers.jnj.com/en/jobs?search={title}&country=United+States",
        "enabled": True,
    },
    {
        "company_name": "FedEx",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://careers.fedex.com/jobs",
        "search_url_template": "https://careers.fedex.com/jobs#q={title}&t=Jobs",
        "enabled": True,
    },
    {
        "company_name": "Energy Transfer",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.energytransfer.com/careers/",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "State Farm Insurance",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.statefarm.com/main/",
        "search_url_template": "https://jobs.statefarm.com/main/jobs?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "PepsiCo",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.pepsico.com/en/careers",
        "search_url_template": "https://www.pepsico.com/en/careers/search?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Wells Fargo",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.wellsfargo.com/about/careers/",
        "search_url_template": "https://www.wellsfargo.com/about/careers/search?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Walt Disney",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.disneycareers.com/",
        "search_url_template": "https://jobs.disneycareers.com/search-jobs/{title}/391/1",
        "enabled": True,
    },
    {
        "company_name": "ConocoPhillips",
        "ats_type": "workday",
        "greenhouse_token": None,
        "career_url": "https://conocophillips.wd1.myworkdayjobs.com/External",
        "search_url_template": "https://conocophillips.wd1.myworkdayjobs.com/External?q={title}",
        "enabled": True,
    },
    {
        "company_name": "Procter & Gamble",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.pgcareers.com/",
        "search_url_template": "https://www.pgcareers.com/global/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "General Electric",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.gecareers.com/global/en/search-results",
        "search_url_template": "https://jobs.gecareers.com/global/en/search-results?keywords={title}",
        "enabled": True,
    },
    {
        "company_name": "Albertsons",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.albertsons.com/careers.html",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Lenovo",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.lenovo.com/en_US/careers",
        "search_url_template": None,
        "enabled": True,
    },

    # ── Ashby ────────────────────────────────────────────────────────────────
    {
        "company_name": "Edison Scientific",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Edison%20Scientific",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Mosaic",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Mosaic",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "InfluxData",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/InfluxData",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Snowflake",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Snowflake",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Airbyte",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Airbyte",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Confluent",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Confluent",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Boomi",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Boomi",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "UiPath",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/UiPath",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Plaid",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Plaid",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Ramp",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Ramp",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Deel",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Deel",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Leapsome",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Leapsome",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Buffer",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Buffer",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Talkdesk",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/Talkdesk",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "FullStory",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/FullStory",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Notion",
        "ats_type": "ashby",
        "greenhouse_token": None,
        "career_url": "https://jobs.ashbyhq.com/notion",
        "search_url_template": None,
        "enabled": True,
    },

    # ── Greenhouse (auto-detected) ───────────────────────────────────────────
    {
        "company_name": "Lyft",
        "ats_type": "greenhouse",
        "greenhouse_token": "lyft",
        "career_url": "https://boards.greenhouse.io/lyft",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Airbnb",
        "ats_type": "greenhouse",
        "greenhouse_token": "airbnb",
        "career_url": "https://boards.greenhouse.io/airbnb",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "VeriSign",
        "ats_type": "greenhouse",
        "greenhouse_token": "verisign",
        "career_url": "https://boards.greenhouse.io/verisign",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "GoDaddy",
        "ats_type": "greenhouse",
        "greenhouse_token": "godaddy",
        "career_url": "https://boards.greenhouse.io/godaddy",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Fastly",
        "ats_type": "greenhouse",
        "greenhouse_token": "fastly",
        "career_url": "https://boards.greenhouse.io/fastly",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Cloudflare",
        "ats_type": "greenhouse",
        "greenhouse_token": "cloudflare",
        "career_url": "https://boards.greenhouse.io/cloudflare",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Zscaler",
        "ats_type": "greenhouse",
        "greenhouse_token": "zscaler",
        "career_url": "https://boards.greenhouse.io/zscaler",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "New Relic",
        "ats_type": "greenhouse",
        "greenhouse_token": "newrelic",
        "career_url": "https://boards.greenhouse.io/newrelic",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Elastic",
        "ats_type": "greenhouse",
        "greenhouse_token": "elastic",
        "career_url": "https://boards.greenhouse.io/elastic",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Sumo Logic",
        "ats_type": "greenhouse",
        "greenhouse_token": "sumologic",
        "career_url": "https://boards.greenhouse.io/sumologic",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Twilio",
        "ats_type": "greenhouse",
        "greenhouse_token": "twilio",
        "career_url": "https://boards.greenhouse.io/twilio",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Bandwidth",
        "ats_type": "greenhouse",
        "greenhouse_token": "bandwidth",
        "career_url": "https://boards.greenhouse.io/bandwidth",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Qualtrics",
        "ats_type": "greenhouse",
        "greenhouse_token": "qualtrics",
        "career_url": "https://boards.greenhouse.io/qualtrics",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "HubSpot",
        "ats_type": "greenhouse",
        "greenhouse_token": "hubspot",
        "career_url": "https://boards.greenhouse.io/hubspot",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Braze",
        "ats_type": "greenhouse",
        "greenhouse_token": "braze",
        "career_url": "https://boards.greenhouse.io/braze",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Klaviyo",
        "ats_type": "greenhouse",
        "greenhouse_token": "klaviyo",
        "career_url": "https://boards.greenhouse.io/klaviyo",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Dropbox",
        "ats_type": "greenhouse",
        "greenhouse_token": "dropbox",
        "career_url": "https://boards.greenhouse.io/dropbox",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "MongoDB",
        "ats_type": "greenhouse",
        "greenhouse_token": "mongodb",
        "career_url": "https://boards.greenhouse.io/mongodb",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "SingleStore",
        "ats_type": "greenhouse",
        "greenhouse_token": "singlestore",
        "career_url": "https://boards.greenhouse.io/singlestore",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Databricks",
        "ats_type": "greenhouse",
        "greenhouse_token": "databricks",
        "career_url": "https://boards.greenhouse.io/databricks",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Fivetran",
        "ats_type": "greenhouse",
        "greenhouse_token": "fivetran",
        "career_url": "https://boards.greenhouse.io/fivetran",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "GitLab",
        "ats_type": "greenhouse",
        "greenhouse_token": "gitlab",
        "career_url": "https://boards.greenhouse.io/gitlab",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "JFrog",
        "ats_type": "greenhouse",
        "greenhouse_token": "jfrog",
        "career_url": "https://boards.greenhouse.io/jfrog",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Blend",
        "ats_type": "greenhouse",
        "greenhouse_token": "blend",
        "career_url": "https://boards.greenhouse.io/blend",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Marqeta",
        "ats_type": "greenhouse",
        "greenhouse_token": "marqeta",
        "career_url": "https://boards.greenhouse.io/marqeta",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Stripe",
        "ats_type": "greenhouse",
        "greenhouse_token": "stripe",
        "career_url": "https://boards.greenhouse.io/stripe",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Brex",
        "ats_type": "greenhouse",
        "greenhouse_token": "brex",
        "career_url": "https://boards.greenhouse.io/brex",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Gusto",
        "ats_type": "greenhouse",
        "greenhouse_token": "gusto",
        "career_url": "https://boards.greenhouse.io/gusto",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Remote",
        "ats_type": "greenhouse",
        "greenhouse_token": "remote",
        "career_url": "https://boards.greenhouse.io/remote",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Lattice",
        "ats_type": "greenhouse",
        "greenhouse_token": "lattice",
        "career_url": "https://boards.greenhouse.io/lattice",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Culture Amp",
        "ats_type": "greenhouse",
        "greenhouse_token": "cultureamp",
        "career_url": "https://boards.greenhouse.io/cultureamp",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Anaplan",
        "ats_type": "greenhouse",
        "greenhouse_token": "anaplan",
        "career_url": "https://boards.greenhouse.io/anaplan",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Host Analytics",
        "ats_type": "greenhouse",
        "greenhouse_token": "hostanalytics",
        "career_url": "https://boards.greenhouse.io/hostanalytics",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Ivalua",
        "ats_type": "greenhouse",
        "greenhouse_token": "ivalua",
        "career_url": "https://boards.greenhouse.io/ivalua",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Five9",
        "ats_type": "greenhouse",
        "greenhouse_token": "five9",
        "career_url": "https://boards.greenhouse.io/five9",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Sprout Social",
        "ats_type": "greenhouse",
        "greenhouse_token": "sproutsocial",
        "career_url": "https://boards.greenhouse.io/sproutsocial",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Hootsuite",
        "ats_type": "greenhouse",
        "greenhouse_token": "hootsuite",
        "career_url": "https://boards.greenhouse.io/hootsuite",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Similarweb",
        "ats_type": "greenhouse",
        "greenhouse_token": "similarweb",
        "career_url": "https://boards.greenhouse.io/similarweb",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Yotpo",
        "ats_type": "greenhouse",
        "greenhouse_token": "yotpo",
        "career_url": "https://boards.greenhouse.io/yotpo",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Trustpilot",
        "ats_type": "greenhouse",
        "greenhouse_token": "trustpilot",
        "career_url": "https://boards.greenhouse.io/trustpilot",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Amplitude",
        "ats_type": "greenhouse",
        "greenhouse_token": "amplitude",
        "career_url": "https://boards.greenhouse.io/amplitude",
        "search_url_template": None,
        "enabled": True,
    },
    {
        "company_name": "Mixpanel",
        "ats_type": "greenhouse",
        "greenhouse_token": "mixpanel",
        "career_url": "https://boards.greenhouse.io/mixpanel",
        "search_url_template": None,
        "enabled": True,
    },

    # ── Disabled (bad/unverified portal URLs) ────────────────────────────────
    {
        "company_name": "Walgreens Boots Alliance",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.walgreens.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "UPS",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://www.jobs-ups.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "Lowe's",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://talent.lowes.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "MetLife",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.metlife.com/",
        "search_url_template": None,
        "enabled": False,
    },
    {
        "company_name": "Comcast",
        "ats_type": "generic",
        "greenhouse_token": None,
        "career_url": "https://jobs.comcast.com/",
        "search_url_template": "https://jobs.comcast.com/search-jobs/{title}",
        "enabled": False,
    },
]
